import { Company } from "./types";

export const placementData: Company[] = [
    { id: 1, name: "4th Orbit (P) Ltd.", date: "4th Sept'2025", cgpa: "6", role: "AI Product Development Intern", stipend: "₹5k-15k / month", duration: "6-8 Months", ctc: "₹5.00 - ₹6.00 LPA", location: "Remote / Bengaluru" },
    { id: 2, name: "AbsoluteLabs", date: "9th Jan'2025", cgpa: "6", role: "Intern", stipend: "₹20,000 / month", duration: "6 Months", ctc: "₹5.00 LPA", location: "Hyderabad" },
    { id: 3, name: "Accenture", date: "11th Sept'2025", cgpa: "6", role: "Associate Software Engineer / Advanced ASE", stipend: "-", duration: "-", ctc: "₹4.2 / 6.5 / 11.2 LPA", location: "Multiple Locations" },
    { id: 4, name: "Aditya Birla", date: "24th July'2025", cgpa: "6", role: "Data Science / Data Engineering", stipend: "₹25,000 - ₹30,000 / month", duration: "6 Months", ctc: "₹10.00 LPA", location: "Bengaluru" },
    { id: 5, name: "ADP", date: "23rd Apr'2025", cgpa: "6", role: "Software Development Intern", stipend: "₹30,000 / month", duration: "3 Months", ctc: "₹7.50 LPA", location: "Hyderabad" },
    { id: 6, name: "Aethereus Consulting", date: "24th Sept'2025", cgpa: "6", role: "Intern (Salesforce Technology)", stipend: "₹12,000 / month", duration: "6 Months", ctc: "₹6.00 LPA", location: "-" },
    { id: 7, name: "Afford Technologies", date: "27th Mar'2025", cgpa: "", role: "Full Stack Developer", stipend: "₹3.00 LPA (Probation)", duration: "Probation", ctc: "₹10.00 LPA", location: "Hyderabad" },
    { id: 8, name: "Algo University", date: "22nd April'2025", cgpa: "", role: "SWE Intern / Technical Solution Engineer", stipend: "₹30,000 - ₹80,000 / month", duration: "2 Months", ctc: "₹10.00 - ₹22.00 LPA", location: "Remote/Hyderabad" },
    { id: 9, name: "AntBox", date: "18th Sept'2025", cgpa: "7", role: "AI & Automation Developer", stipend: "₹25,000 / month", duration: "-", ctc: "₹8.00 LPA", location: "Bhubaneswar" },
    { id: 10, name: "AP Moller Maersk", date: "29th May'2025", cgpa: "7", role: "IT Infrastructure Intern", stipend: "₹50,000 / month", duration: "12 Months", ctc: "₹10.83 LPA", location: "Bengaluru" },
    { id: 11, name: "Appvin", date: "20th Nov'2025", cgpa: "7", role: "Software Developer Trainee", stipend: "₹15,000 / month", duration: "6 Months", ctc: "₹5.00 LPA", location: "Noida" },
    { id: 12, name: "Arihant Capital", date: "5th Dec'2025", cgpa: "6", role: "QA / Backend / Frontend Intern", stipend: "₹10,000 / month", duration: "3-6 Months", ctc: "₹4.00 - ₹6.00 LPA", location: "Mumbai" },
    { id: 13, name: "Aristok Technologies", date: "13th Sept'2025", cgpa: "6", role: "Business Analyst / Digital Marketing", stipend: "₹15,000 / month", duration: "6 Months", ctc: "₹4.51 LPA", location: "Pune" },
    { id: 14, name: "ASBL", date: "14th Nov'2025", cgpa: "8.5", role: "Software Engineer (L1)", stipend: "₹40,000 / month", duration: "6 Months", ctc: "₹10.00 LPA", location: "Hyderabad" },
    { id: 15, name: "Aurus Tech", date: "8th Dec'2025", cgpa: "6", role: "Developer/Tester/Support", stipend: "-", duration: "-", ctc: "₹4.00 LPA", location: "Pune" },
    { id: 16, name: "Bain & Company", date: "14th Aug'2025", cgpa: "6", role: "Intern", stipend: "₹2,70,000 (Total)", duration: "6 Months", ctc: "₹15.68 LPA", location: "Bengaluru / Gurgaon" },
    { id: 17, name: "Bespoke", date: "5th Jan'2026", cgpa: "6", role: "SDE Intern", stipend: "₹12,500 / month", duration: "-", ctc: "₹6.40 LPA", location: "Bengaluru" },
    { id: 18, name: "BEUMER", date: "11th Dec'2025", cgpa: "7.5", role: "Graduate Engineer Trainee", stipend: "-", duration: "-", ctc: "₹4.20 LPA", location: "-" },
    { id: 19, name: "Binocs", date: "14th July'2025", cgpa: "6", role: "Business Operations Analyst Intern", stipend: "₹25,000 - ₹30,000 / month", duration: "6 Months", ctc: "₹8.50 LPA", location: "Bengaluru" },
    { id: 20, name: "Blackbaud", date: "23rd Dec'2025", cgpa: "7.5", role: "Technology Professional", stipend: "-", duration: "-", ctc: "₹12.00 LPA", location: "Hyderabad" },
    { id: 21, name: "Bluekaktus", date: "31st July'2025", cgpa: "8", role: "Intern - Marketing / CEO Office", stipend: "₹25,000 / month", duration: "6 Months", ctc: "₹8.00 LPA", location: "-" },
    { id: 22, name: "BNP Paribas", date: "13th Aug'2025", cgpa: "7", role: "Intern", stipend: "₹50,000 / month", duration: "6 Months", ctc: "₹7.50 LPA", location: "Bengaluru/Chennai/Mumbai" },
    { id: 23, name: "BNY", date: "29th July'2025", cgpa: "7.5", role: "Intern", stipend: "₹75,000 / month", duration: "8-10 Weeks", ctc: "₹22.00 LPA", location: "Pune / Chennai" },
    { id: 24, name: "Booking Holdings", date: "14th July'2025", cgpa: "", role: "Intern", stipend: "₹75,000 / month", duration: "6 Months", ctc: "₹16.20 LPA", location: "Bengaluru" },
    { id: 25, name: "Bounteous x Accolite", date: "10th Oct'2025", cgpa: "6", role: "Software Engineer", stipend: "₹25,000 / month", duration: "6 Months", ctc: "₹6.00 LPA", location: "Multiple Locations" },
    { id: 26, name: "Brakes India P Ltd", date: "6th Sept'2025", cgpa: "7.5", role: "Graduate Engineer Trainee", stipend: "₹15,000 / month", duration: "-", ctc: "₹3.79 - ₹5.13 LPA", location: "Multiple Locations" },
    { id: 27, name: "Brillio", date: "9th Jan'2026", cgpa: "6", role: "Software Engineer", stipend: "₹30,000 / month", duration: "6 Months", ctc: "₹15.00 LPA", location: "Bengaluru" },
    { id: 28, name: "CADFEM", date: "19th Nov'2025", cgpa: "6.5", role: "Graduate Engineering Trainee", stipend: "₹15,000 / month", duration: "12 Months", ctc: "₹4.00 LPA", location: "Hyderabad" },
    { id: 29, name: "Capgemini", date: "2nd Sept'2025", cgpa: "", role: "Software Engineer / SAP Consultant", stipend: "-", duration: "-", ctc: "₹4.25 - ₹7.50 LPA", location: "Multiple Locations" },
    { id: 30, name: "Caterpillar", date: "3rd Oct'2025", cgpa: "7.5", role: "Corporate Intern / Software Engineer", stipend: "₹20,000 / month", duration: "6 Months", ctc: "₹14.56 LPA", location: "Bengaluru / Chennai" },
    { id: 31, name: "Chubb", date: "31st July'2025", cgpa: "7", role: "Associate Engineer Trainee", stipend: "₹35,000 / month", duration: "6 Months", ctc: "₹10.00 - ₹11.60 LPA", location: "Hyderabad/Bengaluru/Bhubaneswar" },
    { id: 32, name: "Cisco", date: "4th June'2025", cgpa: "", role: "Software Engineer (Code-a-thon)", stipend: "-", duration: "-", ctc: "₹25.00 LPA", location: "Bengaluru" },
    { id: 33, name: "ClearTax", date: "19th Dec'2025", cgpa: "6", role: "Sales Development Representative", stipend: "₹25,000 / month", duration: "6 Months", ctc: "₹8.00 LPA", location: "-" },
    { id: 34, name: "Clinion", date: "18th Sept'2025", cgpa: "8", role: "GenAI Interns", stipend: "₹3.00 LPA", duration: "12 Months", ctc: "₹6.00 - ₹6.50 LPA", location: "Hyderabad" },
    { id: 35, name: "CME Group", date: "31st July'2025", cgpa: "7", role: "Intern", stipend: "₹55,000 / month", duration: "5-6 Months", ctc: "₹11.00 LPA", location: "Bengaluru" },
    { id: 36, name: "Coditas Solution", date: "16th Sept'2025", cgpa: "6.5", role: "Intern (Software Development)", stipend: "₹11,000 / month", duration: "6 Months", ctc: "₹4.50 LPA", location: "Pune" },
    { id: 37, name: "Coforge", date: "18th Dec'2025", cgpa: "6.5", role: "Graduate Engineer Trainee", stipend: "-", duration: "-", ctc: "₹4.25 LPA", location: "-" },
    { id: 38, name: "Cognida.ai", date: "22nd Sept'2025", cgpa: "7", role: "Software Developer", stipend: "₹20,000 - ₹25,000 / month", duration: "4-6 Months", ctc: "₹7.00 LPA", location: "Hyderabad" },
    { id: 39, name: "Cognizant", date: "11th Nov'2025", cgpa: "7", role: "GenC Next / GenC Pro", stipend: "-", duration: "-", ctc: "₹4.00 - ₹6.75 LPA", location: "Multiple Locations" },
    { id: 40, name: "ConglomerateIT", date: "22nd July'2025", cgpa: "6", role: "Data Science / AI Intern", stipend: "₹25,000 / month", duration: "12 Months", ctc: "₹8.00 LPA", location: "Hyderabad" },
    { id: 41, name: "ContraVault", date: "30th Apr'2025", cgpa: "7", role: "Full Stack Developer Intern", stipend: "₹20,000 / month", duration: "2 Months", ctc: "₹9.00 - ₹12.00 LPA", location: "Bengaluru" },
    { id: 42, name: "Dal.ai", date: "14th Nov'2025", cgpa: "6", role: "Intern", stipend: "No stipend", duration: "2 Months", ctc: "₹6.00 - ₹8.00 LPA", location: "Remote" },
    { id: 43, name: "DBS Tech India", date: "20th Mar'2025", cgpa: "7", role: "Apprenticeship Program", stipend: "₹9,000 - ₹36,000 / month", duration: "12 Months", ctc: "₹8.50 LPA", location: "Hyderabad" },
    { id: 44, name: "Deloitte", date: "18th Aug'2025", cgpa: "6", role: "Analyst USI / Analyst IN", stipend: "-", duration: "-", ctc: "₹7.60 LPA", location: "Multiple Locations" },
    { id: 45, name: "Denso", date: "25th Oct'2025", cgpa: "6", role: "Technology Professional", stipend: "₹18,000 / month", duration: "6 Months", ctc: "₹6.90 LPA", location: "Haryana" },
    { id: 46, name: "DHL IT Services", date: "19th Dec'2025", cgpa: "7", role: "Associate Trainee", stipend: "-", duration: "-", ctc: "₹10.00 - ₹12.00 LPA", location: "Indore" },
    { id: 47, name: "Ecolab Group", date: "8th July'2025", cgpa: "7", role: "Entry Level Software Developer", stipend: "-", duration: "-", ctc: "₹9.50 LPA", location: "-" },
    { id: 48, name: "Edoofa", date: "13th Nov'2025", cgpa: "", role: "Management Trainee", stipend: "₹35,000 / month", duration: "9 Months", ctc: "₹8.00 - ₹12.00 LPA", location: "Gurgaon / Punjab" },
    { id: 49, name: "ElectricPe", date: "2nd Nov'2025", cgpa: "", role: "Business Analyst / Program Manager", stipend: "-", duration: "-", ctc: "₹10.00 LPA", location: "-" },
    { id: 50, name: "Engati", date: "17th Oct'2025", cgpa: "6", role: "Forward Deployed Engineer Intern", stipend: "₹30,000 / month", duration: "6 Months", ctc: "₹6.00 - ₹8.00 LPA", location: "Bengaluru" },
    { id: 51, name: "EPAM", date: "8th July'2025", cgpa: "7", role: "Intern", stipend: "₹30,000 / month", duration: "6 Months", ctc: "₹8.50 LPA", location: "Multiple Locations" },
    { id: 52, name: "Equal", date: "30th Aug'2025", cgpa: "8.5", role: "Full Stack Developer-Intern", stipend: "₹35,000 - ₹40,000 / month", duration: "6 Months", ctc: "₹12.00 - ₹14.00 LPA", location: "Hyderabad" },
    { id: 53, name: "Ericsson", date: "19th Nov'2025", cgpa: "6", role: "Intern", stipend: "₹25,000 / month", duration: "6 Months", ctc: "₹4.67 LPA", location: "Multiple Locations" },
    { id: 54, name: "EY", date: "13th Dec'2025", cgpa: "6.5", role: "Senior Analyst (Technology Consulting)", stipend: "-", duration: "-", ctc: "₹6.48 LPA", location: "Multiple Locations" },
    { id: 55, name: "Factset", date: "15th Oct'2025", cgpa: "7", role: "Software Engineer Intern", stipend: "₹30,000 / month", duration: "6 Months", ctc: "₹11.99 LPA", location: "Hyderabad" },
    { id: 56, name: "Fareye Tech", date: "22nd Oct'2025", cgpa: "6", role: "SDE-Intern", stipend: "₹25,000 / month", duration: "6 Months", ctc: "₹7.00 LPA", location: "-" },
    { id: 57, name: "FICO", date: "3rd July'2025", cgpa: "7", role: "Education-Intern", stipend: "-", duration: "12 Months", ctc: "₹9.00 LPA", location: "Bengaluru" },
    { id: 58, name: "FMI", date: "4th Dec'2025", cgpa: "6", role: "Associate Consultant", stipend: "-", duration: "-", ctc: "₹4.50 LPA", location: "Pune" },
    { id: 59, name: "Forma.ai", date: "5th Mar'2025", cgpa: "8.5", role: "Customer Operations Analyst Intern", stipend: "₹40,000 / month", duration: "12 Months", ctc: "₹13.00 LPA", location: "Pune" },
    { id: 60, name: "FORMI", date: "13th May'2025", cgpa: "7.5", role: "Agent Reliability Engineer", stipend: "₹27,000 - ₹30,000 / month", duration: "6 Months", ctc: "₹8.00 LPA", location: "Bengaluru" },
    { id: 61, name: "Fractal", date: "31st July'2025", cgpa: "7", role: "Imagineer", stipend: "-", duration: "-", ctc: "₹7.50 LPA", location: "Multiple Locations" },
    { id: 62, name: "FWC", date: "4th Oct'2025", cgpa: "", role: "AI/ML with Fullstack Engineer", stipend: "₹25,000 / month", duration: "3 Months", ctc: "₹8.00 - ₹10.00 LPA", location: "Bengaluru" },
    { id: 63, name: "GoComet", date: "26th Nov'2025", cgpa: "6", role: "Sales Development Representative", stipend: "-", duration: "-", ctc: "₹7.00 LPA", location: "Mumbai" },
    { id: 64, name: "GreyOrange", date: "3rd Sept'2025", cgpa: "6", role: "Intern-Program Management", stipend: "₹25,000 / month", duration: "6 Months", ctc: "₹6.00 - ₹7.00 LPA", location: "Gurugram" },
    { id: 65, name: "GyanSys", date: "20th Aug'2025", cgpa: "8", role: "Software Engineer Trainee", stipend: "₹25,000 / month", duration: "6 Months", ctc: "₹6.00 LPA", location: "-" },
    { id: 66, name: "H&R Block", date: "7th Aug'2025", cgpa: "7", role: "Associate Software Engineer", stipend: "-", duration: "-", ctc: "₹5.42 LPA", location: "Trivandrum" },
    { id: 67, name: "HAI", date: "5th Jan'2026", cgpa: "8", role: "Internship cum PPO", stipend: "₹25,000 / month", duration: "6 Months", ctc: "₹6.00 LPA", location: "Multiple Locations" },
    { id: 68, name: "Hashedin Technologies", date: "12th Sept'2025", cgpa: "8", role: "Trainee Engineer - Intern", stipend: "₹25,000 / month", duration: "2 Months", ctc: "₹8.10 LPA", location: "Bengaluru/Gurgaon" },
    { id: 69, name: "HighRadius", date: "20th Mar'2025", cgpa: "", role: "Consulting / Product Development / Sales", stipend: "₹22,000 / month", duration: "10 Months", ctc: "₹8.00 LPA", location: "-" },
    { id: 70, name: "Hike", date: "24th July'2025", cgpa: "7.5", role: "SDE DevOps Intern / Data Engineering", stipend: "₹40,000 / month", duration: "6-12 Months", ctc: "₹16.73 - ₹42.59 LPA", location: "Remote" },
    { id: 71, name: "HiLo Maritime", date: "15th Dec'2025", cgpa: "8", role: "Intern", stipend: "₹40,000 / month", duration: "2 Months", ctc: "Will be informed", location: "Remote" },
    { id: 72, name: "Hire Quotient", date: "17th Dec'2025", cgpa: "6.5", role: "Intern (Backend / App Developer)", stipend: "₹40,000 - ₹60,000 / month", duration: "3-6 Months", ctc: "₹12.00 - ₹15.00 LPA", location: "Bengaluru" },
    { id: 73, name: "Hughes Systique Corp", date: "10th July'2025", cgpa: "8", role: "Associate Engineer", stipend: "₹20,000 / month", duration: "6 Months", ctc: "₹10.06 LPA", location: "Gurgaon" },
    { id: 74, name: "Human Resocia", date: "23rd Aug'2025", cgpa: "8.8", role: "Data Scientist / Software Engineer", stipend: "-", duration: "-", ctc: "₹42.37 - ₹44.52 LPA", location: "Japan" },
    { id: 75, name: "Hyperbots Inc", date: "19th April'2025", cgpa: "", role: "Software Developer Intern", stipend: "₹35,000 / month", duration: "12 Months", ctc: "₹8.40 LPA", location: "Bengaluru" },
    { id: 76, name: "HyperVerge", date: "18th Dec'2025", cgpa: "6", role: "Machine/Deep Learning Intern", stipend: "₹45,000 / month", duration: "6 Months", ctc: "₹14.00 - ₹18.00 LPA", location: "Bengaluru" },
    { id: 77, name: "IBM Consulting", date: "30th Aug'2025", cgpa: "6", role: "Associate System Engineer", stipend: "-", duration: "-", ctc: "₹4.50 LPA", location: "Multiple Locations" },
    { id: 78, name: "Info Edge (Naukri)", date: "27th Sept'2025", cgpa: "", role: "SDET", stipend: "₹30,000 / month", duration: "-", ctc: "₹10.00 LPA", location: "Noida" },
    { id: 79, name: "Infocepts", date: "6th Nov'2025", cgpa: "6", role: "Intern / Trainee", stipend: "₹20,000 / month", duration: "-", ctc: "₹5.50 - ₹7.00 LPA", location: "Pune / Chennai / Bengaluru" },
    { id: 80, name: "Infosys", date: "15th Nov'2025", cgpa: "", role: "DSE and SP L1/L2/L3", stipend: "-", duration: "-", ctc: "₹7 / 10 / 16 / 21 LPA", location: "Multiple Locations" },
    { id: 81, name: "Insight Global", date: "16th Oct'2025", cgpa: "7", role: "Software Engineer Intern", stipend: "₹30,000 / month", duration: "6 Months", ctc: "₹6.00 LPA", location: "Hyderabad" },
    { id: 82, name: "Integreon", date: "1st Jan'2026", cgpa: "6", role: "Analyst- Functional Consultant", stipend: "-", duration: "-", ctc: "₹3.60 - ₹4.00 LPA", location: "Bhubaneswar" },
    { id: 83, name: "Intellect Design Arena", date: "8th Dec'2025", cgpa: "6", role: "Graduate Trainee", stipend: "-", duration: "-", ctc: "₹5.00 LPA", location: "Multiple Locations" },
    { id: 84, name: "Intellibotics Ltd", date: "20th Nov'2025", cgpa: "6", role: "Associate Software Engineer", stipend: "₹25,000 / month", duration: "6 Months", ctc: "₹6.50 LPA", location: "Chennai" },
    { id: 85, name: "ION Group", date: "12th July'2025", cgpa: "7.5", role: "Software Developer / Technical Analyst", stipend: "-", duration: "-", ctc: "₹17.30 LPA", location: "Multiple Locations" },
    { id: 86, name: "IRIS Business Services", date: "23rd June'2025", cgpa: "7.5", role: "Pre-Sales Consultant Intern", stipend: "₹25,000 / month", duration: "11 Months", ctc: "₹6.50 LPA", location: "Hyderabad" },
    { id: 87, name: "IRIS Carbon", date: "18th Sept'2025", cgpa: "7.5", role: "Sales Development Rockstar", stipend: "₹25,000 / month", duration: "12 Months", ctc: "₹5.50 LPA", location: "Hyderabad" },
    { id: 88, name: "Josh Software", date: "5th July'2025", cgpa: "", role: "Intern", stipend: "₹15,000 / month", duration: "6 Months", ctc: "₹5.40 LPA", location: "Pune" },
    { id: 89, name: "JP Morgan Chase", date: "21st Mar'2025", cgpa: "8.5", role: "Software Engineer", stipend: "-", duration: "-", ctc: "₹19.75 LPA", location: "-" },
    { id: 90, name: "JSW Energy", date: "10th Oct'2025", cgpa: "6", role: "Graduate Engineer Trainee", stipend: "-", duration: "12 Months", ctc: "₹8.00 - ₹8.50 LPA", location: "Mumbai" },
    { id: 91, name: "Kaara Technology", date: "10th July'2025", cgpa: "6", role: "Business Development Specialist", stipend: "₹25,000 / month", duration: "12 Months", ctc: "₹6.00 LPA", location: "Hyderabad" },
    { id: 92, name: "Keploy", date: "6th May'2025", cgpa: "", role: "Fellow -> Intern", stipend: "₹20,000 - ₹35,000 / month", duration: "4-6 Months", ctc: "₹10.00 LPA", location: "Virtual" },
    { id: 93, name: "Kickdrum", date: "10th Oct'2025", cgpa: "8", role: "Software Developer", stipend: "₹35,000 / month", duration: "6 Months", ctc: "₹15.73 LPA", location: "Bengaluru" },
    { id: 94, name: "Kovair Software", date: "15th Nov'2025", cgpa: "6", role: "Trainee", stipend: "-", duration: "6 Months", ctc: "₹3.75 - ₹5.00 LPA", location: "Kolkata" },
    { id: 95, name: "KPMG", date: "24th Aug'2025", cgpa: "6", role: "Intern (GovTech / AppsTech)", stipend: "₹20,000 / month", duration: "6 Months", ctc: "₹5.00 - ₹6.00 LPA", location: "Multiple Locations" },
    { id: 96, name: "Kristellar Aerospace", date: "11th July'2025", cgpa: "7.5", role: "Cybersecurity Analyst / FPGA Developer", stipend: "₹20,000 / month", duration: "3 Months", ctc: "₹8.00 LPA", location: "Bhubaneswar" },
    { id: 97, name: "Leadrat", date: "5th Jan'2026", cgpa: "6.5", role: "Sales Development Engineer", stipend: "₹20,000 / month", duration: "-", ctc: "₹8.00 LPA", location: "Bengaluru" },
    { id: 98, name: "LG Soft", date: "15th May'2025", cgpa: "7", role: "Intern", stipend: "₹30,000 / month", duration: "6-10 Months", ctc: "₹7.50 LPA", location: "Bengaluru" },
    { id: 99, name: "Listenlights", date: "29th Nov'2025", cgpa: "6", role: "Intern", stipend: "₹25,000 / month", duration: "6 Months", ctc: "₹7.50 LPA", location: "-" },
    { id: 100, name: "LTI Mindtree", date: "6th Sept'2025", cgpa: "", role: "Graduate Engineer Trainee", stipend: "-", duration: "-", ctc: "₹4.00 LPA", location: "Multiple Locations" },
    { id: 101, name: "Lumber", date: "6th May'2025", cgpa: "8", role: "Full Stack Developer Intern", stipend: "₹55,000 / month", duration: "12 Months", ctc: "₹14.00 LPA", location: "Bengaluru" },
    { id: 102, name: "Lumen", date: "30th July'2025", cgpa: "7.5", role: "Intern", stipend: "₹30,000 / month", duration: "6 Months", ctc: "₹7.00 LPA", location: "-" },
    { id: 103, name: "Maruti Suzuki", date: "29th Oct'2025", cgpa: "6.5", role: "Graduate Engineer Trainee", stipend: "-", duration: "12 Months", ctc: "₹12.85 LPA", location: "Multiple Locations" },
    { id: 104, name: "Marvell", date: "25th June'2025", cgpa: "7", role: "Software/Firmware / Analog Intern", stipend: "₹40,000 - ₹55,000 / month", duration: "6-11 Months", ctc: "₹14.00 - ₹16.30 LPA", location: "Mumbai" },
    { id: 105, name: "MarketsandMarkets", date: "27th Aug'2025", cgpa: "6", role: "Full Stack Engineer Intern", stipend: "₹30,000 / month", duration: "12 Months", ctc: "₹8.00 LPA", location: "Bengaluru/Pune" },
    { id: 106, name: "MathCo", date: "11th July'2025", cgpa: "6.5", role: "Trainee Analyst", stipend: "-", duration: "-", ctc: "₹5.50 - ₹12.50 LPA", location: "Bengaluru" },
    { id: 107, name: "MediBuddy", date: "8th Jan'2026", cgpa: "6", role: "Business Trainee", stipend: "-", duration: "-", ctc: "₹6.00 LPA", location: "Bengaluru" },
    { id: 108, name: "Meesho", date: "30th Aug'2025", cgpa: "6", role: "Business Analyst", stipend: "₹70,000 / month", duration: "6 Months", ctc: "₹23.50 LPA", location: "Bengaluru" },
    { id: 109, name: "Mindfire Digital", date: "22nd Nov'2025", cgpa: "6", role: "Intern Software Engineer", stipend: "₹18,000 / month", duration: "6 Months", ctc: "₹4.50 - ₹6.00 LPA", location: "-" },
    { id: 110, name: "Modist Global", date: "24th June'2025", cgpa: "8", role: "Outbound Marketing Analyst", stipend: "₹15,000 / month", duration: "6-12 Months", ctc: "₹6.00 - ₹10.00 LPA", location: "Remote" },
    { id: 111, name: "Morgan Stanley", date: "24th April'2025", cgpa: "8", role: "Apprenticeship Program", stipend: "₹87,000 / month", duration: "6 Months", ctc: "-", location: "Mumbai/Bengaluru" },
    { id: 112, name: "Movate", date: "6th Nov'2025", cgpa: "7", role: "Associate AI/ML / Data Engineer", stipend: "₹25,000 / month", duration: "6 Months", ctc: "₹9.00 LPA", location: "Bengaluru" },
    { id: 113, name: "Mu Sigma", date: "9th Aug'2025", cgpa: "7", role: "Decision Scientist", stipend: "-", duration: "-", ctc: "₹10.00 LPA", location: "-" },
    { id: 114, name: "Murphi.ai", date: "18th Dec'2025", cgpa: "6", role: "Mobile App / QA / AI/ML / UI/UX", stipend: "₹25,000 / month", duration: "6 Months", ctc: "₹5.00 LPA", location: "Bengaluru" },
    { id: 115, name: "Naehas", date: "22nd Nov'2025", cgpa: "6", role: "Software Engineer / QA Engineer", stipend: "₹40,000 / month", duration: "6 Months", ctc: "₹9.04 LPA", location: "Gurgaon" },
    { id: 116, name: "Namekart", date: "9th April'2025", cgpa: "7.5", role: "Enterprise Domain Sales / SDE / AI", stipend: "₹30,000 / month", duration: "12 Months", ctc: "₹8.00 - ₹15.00 LPA", location: "Noida" },
    { id: 117, name: "Navikenz", date: "6th Nov'2025", cgpa: "6", role: "Software Engineer", stipend: "₹25,000 / month", duration: "3-4 Months", ctc: "₹6.00 LPA", location: "Noida / Bengaluru" },
    { id: 118, name: "Newgen", date: "5th Dec'2025", cgpa: "6", role: "Application / Software Engineer", stipend: "₹20,000 / month", duration: "6 Months", ctc: "₹4.25 LPA", location: "Delhi NCR / Noida" },
    { id: 119, name: "Nisum", date: "5th Apr'2025", cgpa: "7.5", role: "Web Developer", stipend: "-", duration: "-", ctc: "₹4.20 LPA", location: "-" },
    { id: 120, name: "Noboru World", date: "12th Sept'2025", cgpa: "7", role: "Associate Marketing Manager", stipend: "-", duration: "-", ctc: "₹6.00 LPA", location: "Pune" },
    { id: 121, name: "NOUS Infosystems", date: "21st Aug'2025", cgpa: "8", role: "Intern", stipend: "₹15,000 / month", duration: "6 Months", ctc: "₹5.00 LPA", location: "-" },
    { id: 122, name: "NVIDIA", date: "9th Sept'2025", cgpa: "7.8", role: "System Software Engineering Intern", stipend: "₹80,000 / month", duration: "6 Months", ctc: "-", location: "Pune/Bengaluru/Hyderabad" },
    { id: 123, name: "NxtWave Edge", date: "14th Nov'2025", cgpa: "", role: "Software Development Engineer", stipend: "-", duration: "-", ctc: "₹20.00 - ₹35.00 LPA", location: "Hyd/Mum/Bengaluru" },
    { id: 124, name: "OneBanc", date: "24th June'2025", cgpa: "8", role: "Android/iOS/Full Stack/Data Science", stipend: "₹30,000 / month", duration: "Till June 2026", ctc: "₹8.00 - ₹10.00 LPA", location: "Gurugram" },
    { id: 125, name: "Open Hearing", date: "12th Dec'2025", cgpa: "6", role: "Full Stack Developer", stipend: "₹30,000 / month", duration: "6-11 Months", ctc: "₹12.00 - ₹15.00 LPA", location: "Bengaluru" },
    { id: 126, name: "Optum", date: "29th Oct'2024", cgpa: "7", role: "Technology Development Program", stipend: "₹40,000 / month", duration: "10 Weeks", ctc: "₹18.50 LPA", location: "Gurugram / Hyderabad" },
    { id: 127, name: "Osfin", date: "2nd Nov'2025", cgpa: "8.5", role: "Data Analyst-Intern", stipend: "₹25,000 / month", duration: "6 Months", ctc: "₹6.00 - ₹7.00 LPA", location: "Multiple Locations" },
    { id: 128, name: "PeopleStrong", date: "18th Dec'2025", cgpa: "6.5", role: "Trainee / SDE-1", stipend: "₹50,000 / month", duration: "6 Months", ctc: "₹8.00 LPA", location: "Gurgaon" },
    { id: 129, name: "Pepsales AI", date: "15th May'2025", cgpa: "7", role: "AI/ML Intern / Backend Intern", stipend: "₹25,000 / month", duration: "-", ctc: "₹8.00 LPA", location: "Bengaluru" },
    { id: 130, name: "Philips", date: "24th June'2025", cgpa: "7", role: "Intern", stipend: "₹45,000 - ₹55,000 / month", duration: "12 Months", ctc: "₹11.50 - ₹12.00 LPA", location: "Bengaluru" },
    { id: 131, name: "Pilgrim", date: "23rd May'2025", cgpa: "6", role: "Product Management Intern", stipend: "₹15,000 / month", duration: "6 Months", ctc: "₹8.00 - ₹10.00 LPA", location: "Mumbai" },
    { id: 132, name: "Pine Labs", date: "9th April'2025", cgpa: "8", role: "Software Engineer", stipend: "₹40,000 / month", duration: "10 Months", ctc: "₹11.00 LPA", location: "Multiple Locations" },
    { id: 133, name: "PixelCompute", date: "14th Aug'2025", cgpa: "7", role: "Full Stack Developer - Intern", stipend: "₹20,000 / month", duration: "6 Months", ctc: "₹19.74 LPA", location: "Bhubaneswar" },
    { id: 134, name: "PlaySimple Games", date: "2nd Sept'2025", cgpa: "6.5", role: "Business Analyst / Software Engineer", stipend: "₹30,000 / month", duration: "12 Months", ctc: "₹14.00 LPA", location: "Bengaluru" },
    { id: 135, name: "Propel", date: "6th Jan'2026", cgpa: "7", role: "Retention Marketing Specialist", stipend: "₹25,000 / month", duration: "-", ctc: "₹8.00 - ₹11.00 LPA", location: "Bengaluru" },
    { id: 136, name: "Providence", date: "8th Aug'2024", cgpa: "7.5", role: "Intern", stipend: "₹50,000 / month", duration: "-", ctc: "₹16.00 LPA", location: "Hyderabad" },
    { id: 137, name: "Publicis Sapient", date: "24th Sept'2025", cgpa: "8.5", role: "Trainee Engineer", stipend: "-", duration: "-", ctc: "₹8.47 LPA", location: "Bengaluru / Gurgaon" },
    { id: 138, name: "PwC", date: "5th Jan'2026", cgpa: "6", role: "Specialist RDC - One Consulting Advisory", stipend: "₹30,000 / month", duration: "6 Months", ctc: "₹4.50 LPA", location: "Bhubaneswar" },
    { id: 139, name: "Qualcomm", date: "15th July'2025", cgpa: "6", role: "IT Intern / Cyber Security Intern", stipend: "₹45,000 / month", duration: "6 Months", ctc: "₹8.28 LPA", location: "-" },
    { id: 140, name: "QuadOne Technologies", date: "23rd June'2025", cgpa: "7.5", role: "Business Development Executive", stipend: "₹30,000 / month", duration: "12 Months", ctc: "₹7.20 - ₹8.00 LPA", location: "-" },
    { id: 141, name: "QuickSell & DoubleTick", date: "22nd Aug'2025", cgpa: "6", role: "Support Engineer", stipend: "-", duration: "-", ctc: "₹7.50 LPA", location: "Mumbai" },
    { id: 142, name: "Quinbay", date: "6th Sep'2025", cgpa: "8", role: "Intern", stipend: "₹31,000 / month", duration: "12 Months", ctc: "₹7.50 - ₹10.00 LPA", location: "Bengaluru" },
    { id: 143, name: "Recruit CRM", date: "1st Nov'2025", cgpa: "", role: "Customer Success Associate (CSA)", stipend: "₹20,000 / month", duration: "6 Months", ctc: "₹8.00 LPA", location: "Remote" },
    { id: 144, name: "Remidio Innovative Solutions", date: "27th Nov'2025", cgpa: "6", role: "Graduate Engineer Trainee - Sales", stipend: "₹18,000 / month", duration: "6 Months", ctc: "₹5.00 LPA", location: "Multiple Locations" },
    { id: 145, name: "Restroworks", date: "18th Aug'2025", cgpa: "", role: "MEAN Stack Developer", stipend: "₹26,000 / month", duration: "6 Months", ctc: "₹8.00 - ₹10.00 LPA", location: "Delhi" },
    { id: 146, name: "RnPsoft", date: "22nd April'2025", cgpa: "7", role: "Web Developer / ML / Content", stipend: "₹8,000 - ₹10,000 / month", duration: "6 Months", ctc: "-", location: "Bhubaneswar" },
    { id: 147, name: "Rockwell Automation", date: "12th Dec'2025", cgpa: "7", role: "Graduate Engineer Trainee", stipend: "-", duration: "-", ctc: "₹6.34 LPA", location: "Pune" },
    { id: 148, name: "rtCamp", date: "8th Jan'2026", cgpa: "", role: "Associate Software Engineer", stipend: "₹25,000 / month", duration: "6 Months", ctc: "₹12.00 LPA", location: "Remote" },
    { id: 149, name: "Samsung Electro Mechanics", date: "20th May'2025", cgpa: "6", role: "AI / ML / Full Stack Developer", stipend: "₹35,000 - ₹40,000 / month", duration: "12 Months", ctc: "₹10.00 - ₹12.00 LPA", location: "Bengaluru" },
    { id: 150, name: "Sasken Technologies", date: "11th April'2025", cgpa: "6.5", role: "Summer Intern", stipend: "-", duration: "8 Weeks", ctc: "₹5.00 LPA", location: "Virtual" },
    { id: 151, name: "Seedicon India", date: "4th Oct'2025", cgpa: "", role: "SaaS Product Analyst", stipend: "₹20,000 / month", duration: "3 Months", ctc: "₹4.00 - ₹6.00 LPA", location: "Bengaluru" },
    { id: 152, name: "Shree Cement", date: "2nd Jan'2026", cgpa: "6", role: "Graduate Engineer Trainee", stipend: "-", duration: "-", ctc: "₹5.00 LPA", location: "Multiple Locations" },
    { id: 153, name: "Simetrik", date: "22nd Mar'2025", cgpa: "6.5", role: "Business Development Representative", stipend: "₹25,000 / month", duration: "12 Months", ctc: "₹8.25 LPA", location: "Bhubaneswar" },
    { id: 154, name: "SMS Magic", date: "23rd June'2025", cgpa: "6", role: "Sales Development Intern", stipend: "₹25,000 / month", duration: "6-12 Months", ctc: "₹6.00 - ₹7.00 LPA", location: "Bengaluru" },
    { id: 155, name: "Solidus Lifesciences", date: "12th Dec'2025", cgpa: "7", role: "Python Developers", stipend: "-", duration: "-", ctc: "₹4.00 - ₹6.00 LPA", location: "Gurgaon" },
    { id: 156, name: "State Street", date: "10th Oct'2025", cgpa: "7.5", role: "Intern", stipend: "₹30,000 / month", duration: "6 Months", ctc: "₹8.00 - ₹9.00 LPA", location: "Bengaluru/Hyderabad" },
    { id: 157, name: "Super AGI", date: "27th Nov'2025", cgpa: "7", role: "Software Engineer Intern", stipend: "₹25,000 - ₹30,000 / month", duration: "6 Months", ctc: "₹7.00 - ₹9.00 LPA", location: "Bengaluru" },
    { id: 158, name: "Swiggy", date: "2nd Oct'2025", cgpa: "6", role: "Intern-Engineering / ASDE", stipend: "₹40,000 / month", duration: "6 Months", ctc: "₹11.00 - ₹12.00 LPA", location: "Bengaluru / Remote" },
    { id: 159, name: "Tata Electronics", date: "25th Aug'2025", cgpa: "8", role: "Software Development Intern", stipend: "₹20,000 - ₹30,000 / month", duration: "6 Months", ctc: "₹6.00 LPA", location: "Multiple Locations" },
    { id: 160, name: "Tata Power Odisha", date: "1st Jan'2026", cgpa: "6", role: "Graduate Engineer Trainee - IT", stipend: "-", duration: "-", ctc: "₹6.06 LPA", location: "Odisha" },
    { id: 161, name: "TCS", date: "14th Oct'2025", cgpa: "", role: "Prime/Digital/Ninja (TCS NQT)", stipend: "-", duration: "-", ctc: "₹3.46 - ₹11.59 LPA", location: "Multiple Locations" },
    { id: 162, name: "Techolution", date: "14th July'2025", cgpa: "6", role: "GenAI Intern", stipend: "₹30,000 / month", duration: "12 Months", ctc: "₹8.00 - ₹11.00 LPA", location: "Hyderabad" },
    { id: 163, name: "TEKsystems Global", date: "6th Jan'2026", cgpa: "7", role: "Associate Engineer", stipend: "-", duration: "-", ctc: "₹4.50 - ₹6.00 LPA", location: "-" },
    { id: 164, name: "TensorGo Software", date: "18th July'2025", cgpa: "", role: "Full Stack / Computer Vision Intern", stipend: "₹15,000 / month", duration: "6 Months", ctc: "₹5.00 - ₹6.00 LPA", location: "Hyderabad" },
    { id: 165, name: "Tredence", date: "3rd Sept'2025", cgpa: "6", role: "Analyst Data Science", stipend: "-", duration: "-", ctc: "₹10.00 - ₹12.00 LPA", location: "Multiple Locations" },
    { id: 166, name: "Trilogy Innovations", date: "2nd Sept'2025", cgpa: "6", role: "Software Development Engineer", stipend: "₹75,000 / month", duration: "6 Months", ctc: "₹30.00 LPA", location: "Bengaluru" },
    { id: 167, name: "UKG", date: "27th Oct'2025", cgpa: "7", role: "Customer Experience Intern", stipend: "₹30,000 / month", duration: "6 Months", ctc: "₹12.74 LPA", location: "-" },
    { id: 168, name: "V4c.ai", date: "24th Sept'2025", cgpa: "6", role: "Associate Data Scientist", stipend: "-", duration: "3-6 Months", ctc: "₹5.20 LPA", location: "Pune" },
    { id: 169, name: "Veeva Systems", date: "9th Dec'2025", cgpa: "8", role: "Software Engineer", stipend: "-", duration: "-", ctc: "₹9.00 LPA", location: "Hyderabad" },
    { id: 170, name: "Viasat", date: "9th Oct'2025", cgpa: "7", role: "Software Engineer Intern", stipend: "₹25,000 / month", duration: "3 Months", ctc: "₹9.50 LPA", location: "Hyderabad" },
    { id: 171, name: "Virtusa", date: "16th Sept'2025", cgpa: "6.5", role: "Coder", stipend: "-", duration: "-", ctc: "₹5.00 - ₹6.50 LPA", location: "-" },
    { id: 172, name: "Vivnoavation", date: "2nd Aug'2025", cgpa: "6", role: "Future Leader in US Healthcare", stipend: "₹15,000 / month", duration: "12 Months", ctc: "₹18.00 LPA", location: "Remote" },
    { id: 173, name: "Volvo Group", date: "14th July'2025", cgpa: "6.5", role: "Associate Graduate Engineer", stipend: "-", duration: "-", ctc: "₹7.50 LPA", location: "-" },
    { id: 174, name: "Whatfix", date: "30th July'2025", cgpa: "7.5", role: "Software Engineer", stipend: "₹50,000 / month", duration: "12 Months", ctc: "₹16.00 LPA", location: "Bengaluru" },
    { id: 175, name: "XL Dynamics", date: "11th Nov'2025", cgpa: "6", role: "Financial Analyst", stipend: "-", duration: "-", ctc: "₹4.50 LPA", location: "Multiple Locations" },
    { id: 176, name: "Xperi", date: "12th July'2025", cgpa: "8", role: "Intern – Software Engineer", stipend: "₹50,000 / month", duration: "6 Months", ctc: "-", location: "-" },
    { id: 177, name: "YugaByte", date: "3rd July'2025", cgpa: "8.5", role: "SDET Intern", stipend: "₹80,000 / month", duration: "12 Months", ctc: "₹21.00 LPA", location: "Bengaluru / Pune" },
    { id: 178, name: "Zendatashastra", date: "11th July'2025", cgpa: "7.5", role: "Associate Business Analyst", stipend: "-", duration: "-", ctc: "₹7.00 LPA", location: "Bengaluru" },
    { id: 179, name: "ZenTrades", date: "28th June'2025", cgpa: "", role: "Sales Development Representative", stipend: "₹30,000 / month", duration: "6 Months", ctc: "₹7.50 LPA", location: "Pune" },
    { id: 180, name: "Ziroh Labs", date: "17th June'2025", cgpa: "", role: "C++ Developer", stipend: "-", duration: "-", ctc: "₹12.00 LPA", location: "Bengaluru" },
    { id: 181, name: "ZS Associates", date: "17th Sept'2025", cgpa: "8", role: "Data Engineer / DevOps Engineer Intern", stipend: "₹40,000 / month", duration: "6 Months", ctc: "₹9.00 - ₹10.00 LPA", location: "Pune" },
    { id: 182, name: "Zscaler", date: "16th Oct'2025", cgpa: "7.5", role: "Software Development Intern", stipend: "₹75,000 / month", duration: "May-July 2026", ctc: "-", location: "-" },
    { id: 183, name: "Zycus", date: "28th May'2025", cgpa: "6", role: "Business Development Associate", stipend: "₹27,500 - ₹40,000 / month", duration: "6 Months", ctc: "-", location: "Multiple Locations" },
    { id: 184, name: "Zynetic", date: "4th April'2025", cgpa: "6", role: "Backend / Frontend / Kotlin Developer", stipend: "₹25,000 / month", duration: "3 Months", ctc: "₹8.00 LPA", location: "Delhi / Hyderabad" },
];
